name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  sui-wallet-key:  # key of sui wallet (keep this in your github secret)
    description: 'key of sui wallet'
    required: true
    default: 'xxx'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'